name: Weekly Stock Analysis

on:
  schedule:
    # 매주 토요일 오전 9시 (UTC+9 기준으로는 토요일 오전 9시)
    - cron: '0 0 * * 6'
  workflow_dispatch:  # 수동 실행 가능

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 전체 히스토리 가져오기
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create stock_data directory
      run: mkdir -p stock_data
        
    - name: Run analysis
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        STOCK_NAME: ${{ secrets.STOCK_NAME }}
        DATA_DAYS: ${{ secrets.DATA_DAYS }}
      run: python main.py
      
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
    - name: Commit and push if changed
      run: |
        git add stock_data/
        git diff --staged --quiet || (git commit -m "Update stock data [skip ci]" && git push)
      
    - name: Upload analysis results
      uses: actions/upload-artifact@v3
      with:
        name: stock-data
        path: stock_data/
        retention-days: 7 